language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo $FAVORITE_FOOD
  - echo "with quotes: $FAVORITE_FOOD"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t travis-env-var .
  - docker tag travis-env-var maloef/travis-env-var:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push maloef/travis-env-var